"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PreferenceProvider from "@/context";
/*import { AnimatePresence } from "framer-motion";*/
import { AppProps } from "next/app";
// import { SessionProvider } from "next-auth/react";*/
import { MdClose } from "react-icons/md";
// import { ToastContainer } from "react-toastify";

import "@/styles/globals.css";
import "@/styles/theme.css";
import "react-toastify/dist/ReactToastify.css";

import commands from "@/data/commands";

import CommandPalette from "@/components/CommandPalette/CommandPalette";
import Header from "@/components/Layout/Header";
import Layout from "@/components/Layout/Layout";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PreferenceProvider>
          <CommandPalette data={commands} />
          {/* <SessionProvider session={session}> */}
          {/* <Layout> */}
          {/*<ToastContainer
            toastClassName={() =>
              "relative flex p-1 mt-4 min-h-10 rounded-md justify-between overflow-hidden cursor-pointer bg-hl text-bg border-2 border-hl mx-4"
            }
            bodyClassName={() =>
              "flex px-2 py-2 text-sm font-primary block accent-hl"
            }
            closeButton={() => (
              <MdClose className="text-bg/80 transition-colors duration-200 hover:text-bg" />
            )}
          />*/}
          {/* <AnimatePresence exitBeforeEnter> */}
          {/* <Component {...pageProps} key={router.route} /> */}
          {/* </AnimatePresence> */}
          {/* <RoomProvider> */}
          {/* <ChatProvider> */}
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Navbar />
            {children}
          </main>
          {/* </ChatProvider> */}
          {/* </RoomProvider>  */}
          {/* </Layout> */}
          {/* </SessionProvider> */}
        </PreferenceProvider>
      </body>
    </html>
  );
}
